#!/bin/bash

# Cleanup Redundant Code
# Generated by analyze-redundant-code.ts

echo "🧹 Cleaning up redundant code..."

rm -rf "src/server/websocket/terminal-ws-exec.js"
rm -rf "src/server/websocket/terminal-ws-fallback.js"
rm -rf "src/server/websocket/terminal-ws-simple.js"
rm -rf "src/server/websocket/terminal-ws-stream.js"
rm -rf "src/server/websocket/terminal-ws-upgrade.js"
rm -rf "src/modules/workspace/components/Terminal/TerminalContainer.tsx"
rm -rf "src/modules/workspace/components/Terminal/TerminalContainerV2.tsx"
rm -rf "src/modules/workspace/components/Terminal/XTermView.tsx"
rm -rf "src/backup/terminal-v1"

echo "✅ Cleanup complete!"